name: presentation_displays
description: Flutter plugin for presenting Flutter UI on connected secondary displays.
homepage: https://github.com/ES-fooshen/presentation-displays
repository: https://github.com/ES-fooshen/presentation-displays
version: 1.1.0

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.namit.presentation_displays
        pluginClass: PresentationDisplaysPlugin
      ios:
        pluginClass: PresentationDisplaysPlugin
